version: "3.4"

services:

  enigma-machine:
    container_name: enigma-machine
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - node_modules:/enigma-machine/node_modules
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19003:19003"
      - "19006:19006"
      - "19007:19007"
    environment:
      NODE_ENV: development
      EXPO_USE_DEV_SERVER: 1
    entrypoint: "npm run start"

volumes:
  node_modules:
